on:
  workflow_dispatch:
    inputs:
      environment:
        description: "choose enviroment"
        required: true
        default: "staging"
        type : choice 
        options:
          - staging 
          - production
          
jobs :
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : Deploy Applicaiton
        run: echo "deploying the application...${{inputs.environment}"
